/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from "web3/eth/contract";
import { TransactionObject, BlockType } from "web3/eth/types";
import { Callback, EventLog } from "web3/types";
import { EventEmitter } from "events";
import { Provider } from "web3/providers";

export class MXCToken {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    balanceOf(_owner: string): TransactionObject<string>;

    allowance(_owner: string, _spender: string): TransactionObject<string>;

    vestBalanceOf(
      who: string
    ): TransactionObject<{
      amount: string;
      vestedAmount: string;
      start: string;
      cliff: string;
      vesting: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    approve(
      _spender: string,
      _value: number | string
    ): TransactionObject<boolean>;

    transferFrom(
      _from: string,
      _to: string,
      _value: number | string
    ): TransactionObject<boolean>;

    decreaseApproval(
      _spender: string,
      _subtractedValue: number | string
    ): TransactionObject<boolean>;

    transfer(_to: string, _value: number | string): TransactionObject<boolean>;

    increaseApproval(
      _spender: string,
      _addedValue: number | string
    ): TransactionObject<boolean>;

    grantToken(
      _to: string,
      _amount: number | string,
      _start: number | string,
      _cliff: number | string,
      _vesting: number | string
    ): TransactionObject<boolean>;

    grantTokenStartNow(
      _to: string,
      _amount: number | string,
      _cliffMonths: number | string,
      _vestingMonths: number | string
    ): TransactionObject<boolean>;

    redeemVestableToken(_to: string): TransactionObject<boolean>;

    returnGrantedToken(_amount: number | string): TransactionObject<boolean>;

    name(): TransactionObject<string>;
    totalSupply(): TransactionObject<string>;
    decimals(): TransactionObject<string>;
    symbol(): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    NewTokenGrant(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    VestedTokenRedeemed(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    GrantedTokenReturned(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Approval(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    Transfer(
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ): EventEmitter;

    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: (null | string)[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
  clone(): MXCToken;
}
